### PR TITLE
Remove filename question marks

### PR DESCRIPTION
**Pull request by gavincox**
Removed question marks causing problems in page filenames.

### CODE REVIEW

**Comment by trongate** [comment]
Hi Gavin!  Thanks for this.  I'm going to paste in a comment that I left on another pull request because I think it's important that we are pulling in the same direction with this.  So, please do have a read and let me know if the following information is clear and logical (I suddenly felt like going a bit "Star Trek", for no apparent reason):

START

Hi guys! I can see that we're getting a bit mixed up with regards to having strange characters as part of the file name (for example, question marks). The way to deal with this is to avoid doing anything strange with regards to file names. So, that means, no question marks, no colons, nothing strange whatsoever. As a matter of fact, for the normal docs (.html) pages, I'd like everything to be in lowercase and for words to be separated by an underscore. That means that the file navigation will be fine and we won't have any problems with that.

Of course, the challenge now is that we would need to come up with a nice title for the left hand navigation.

The solution? Edit Docs.php.

Inside the main root directory there's a file named Docs.php that contains a PHP class. That class has a method called build_nice_label(). I encourage you to have a look at it because it's super easy to understand. So, all you would have to do is add strange replace commands as required so that the page label is perfect. For example, $page_label = str_replace('rongate1', 'rongate https://github.com/trongate/trongate-docs/pull/1', $page_label);

I'd be super grateful if you could confirm that this makes sense. If it doesn't, I'll be glad to do a video tutorial.

END


Gavin, I'll wait for confirmation that you're cool with this before doing any more work on the docs. Ahoy!

**Comment by gavincox** [comment]
Ah yeah, I see how this works now. 

I wanted/needed away to add a question mark to the menu link text. 

Unfortunately, even with this method parsing the filename and rewriting the menu item label, I can't see a way of search-replacing to result in a question mark in the final string without adding additional characters to the filename -- only by adding to the Docs.php file very specific instances of titles to add question marks, which could be quite fragile if they change at any point later.)

Not sure.

**Comment by gavincox** [comment]
Ah wait I have a plan. What if we detect ['What', Where, 'Why', When'] at the start of the string and add a ? to the end? Its basic but might just work in context.

**Comment by gavincox** [comment]
function addQuestionMarkIfNeeded($str) {
    // Define an array of question words
    $questionWords = array('What', 'Where', 'When', 'How', 'Why');

    // Convert the string to lowercase for case-insensitive comparison
    $lowercaseStr = strtolower($str);

    // Check if the string starts with any of the question words
    foreach ($questionWords as $word) {
        if (strpos($lowercaseStr, strtolower($word)) === 0) {
            // If it does, add a question mark to the end
            return rtrim($str) . '?';
        }
    }

    // If the string doesn't start with any of the question words, return it as is
    return $str;
}

// Example usage:
$string = "What is the capital of France";
echo addQuestionMarkIfNeeded($string);

**Comment by gavincox** [comment]
EOTM also suggests 'question' words:

Who: Asks about a person's identity.
What: Inquires about an object, action, or concept.
Where: Asks about a location or place.
When: Inquires about a specific time or period.
Why: Seeks the reason or cause for something.
How: Asks about the manner or method of doing something.
Which: Inquires about a specific choice or option.
Whose: Asks about possession or ownership.

**Comment by gavincox** [comment]
Yeah cool. I can work with whatever you think is best. 🙂

**Comment by zatikbalazs** [comment]
I took a look at the `build_nice_label()` method and it completely makes sense to me. No need for a tutorial.

**Comment by gavincox** [comment]
Exit stage left. Apologies for any inconvenience caused.

**Pull request merged**
