### PR TITLE
Fixed invalid file name

### PR DESCRIPTION
**Pull request by zatikbalazs**
Question mark in file name caused 'invalid path' error when running 'git clone'. Removed question mark from the file name to resolve the error.

### CODE REVIEW

**Comment by gavincox** [comment]
There may be more than one of these filenames as I'd thought it worked.

**Comment by gavincox** [comment]
Can you try replacing the ? in the filename with: &quest; . It appears to work here but with that said, it did before.

**Comment by zatikbalazs** [comment]
> Can you try replacing the ? in the filename with: &quest; . It appears to work here but with that said, it did before.

I am using Windows and it doesn't allow ? characters in file names. I think that is the reason for the file path error when cloning the repo. It works with &quest; in the file name but then it looks unsightly. I will let David decide which way to go.

**Comment by DaFa66** [comment]
well done guys 👍

**Comment by trongate** [comment]
Hi guys!  I can see that we're getting a bit mixed up with regards to having strange characters as part of the file name (for example, question marks).  The way to deal with this is to **avoid doing anything strange with regards to file names**.  So, that means, no question marks, no colons, nothing strange whatsoever.  As a matter of fact, for the normal docs (.html) pages, I'd like everything to be in lowercase and for words to be separated by an underscore.  That means that the file navigation will be fine and we won't have any problems with that.  

Of course, the challenge now is that we would need to come up with a nice title for the left hand navigation.

The solution?  **Edit Docs.php**.

Inside the main root directory there's a file named Docs.php that contains a PHP class.  That class has a method called build_nice_label().   I encourage you to have a look at it because it's super easy to understand.  So, all you would have to do is add strange replace commands as required so that the page label is perfect.  For example, $page_label = str_replace('rongate1', 'rongate #1', $page_label);

I'd be super grateful if you could confirm that this makes sense.  If it doesn't, I'll be glad to do a video tutorial.

**Comment by gavincox** [comment]
See comments on PR #24. I think we have a plan.

**Comment by zatikbalazs** [comment]
Hello David! I took a look at the `build_nice_label()` method. Your plan is simple and completely makes sense to me.

**Pull request closed without merging**
